-- Catalogo de valores canonicos y sus variantes conocidas.
-- Generado desde los 1057 viajes de la base; revisar antes de correr en produccion.

create table if not exists valores_canonicos (
  id uuid primary key default gen_random_uuid(),
  campo text not null check (campo in ('lugar','carga')),
  valor text not null,
  creado_en timestamptz not null default now(),
  unique (campo, valor)
);

create table if not exists alias_valores (
  id uuid primary key default gen_random_uuid(),
  campo text not null check (campo in ('lugar','carga')),
  alias text not null,
  canonico_id uuid not null references valores_canonicos(id) on delete cascade,
  creado_en timestamptz not null default now(),
  unique (campo, alias)
);

create index if not exists idx_canonicos_campo on valores_canonicos (campo);
create index if not exists idx_alias_campo on alias_valores (campo);

-- Canonicos ------------------------------------------------------------
insert into valores_canonicos (campo, valor) values
  ('lugar','25 DE MAYO'),
  ('lugar','9 DE JULIO'),
  ('lugar','ABBOTT'),
  ('lugar','ADELIA MARIA'),
  ('lugar','ALBORADA'),
  ('lugar','ALEJO LEDESMA'),
  ('lugar','AMERICA'),
  ('lugar','ARIAS'),
  ('lugar','ARRIBEÑOS'),
  ('lugar','ARROYITO'),
  ('lugar','ARROYO CABRAL'),
  ('lugar','AVELLANEDA'),
  ('lugar','AZUL'),
  ('lugar','BAHIA BLANCA'),
  ('lugar','BAIGORRITA'),
  ('lugar','BALCARCE'),
  ('lugar','BALSA'),
  ('lugar','BANDERA'),
  ('lugar','BELL VILLE'),
  ('lugar','BENITO JUAREZ'),
  ('lugar','BOLIVAR'),
  ('lugar','BRAGADO'),
  ('lugar','BRANDSEN'),
  ('lugar','BS AS'),
  ('lugar','CAMPANA'),
  ('lugar','CARCARAÑA'),
  ('lugar','CARHUE'),
  ('lugar','CARLOS CASARES'),
  ('lugar','CARMEN DE ARECO'),
  ('lugar','CASILDA'),
  ('lugar','CATRILO'),
  ('lugar','CAÑADA DE GOMEZ'),
  ('lugar','CAÑADA SECA'),
  ('lugar','CEBALLOS'),
  ('lugar','CHABAS'),
  ('lugar','CHACABUCO'),
  ('lugar','CHAJARI'),
  ('lugar','CHAPUY'),
  ('lugar','CHAPUY Y TEODELINA'),
  ('lugar','CHARATA'),
  ('lugar','CHASCOMUS'),
  ('lugar','CHIVILCOY'),
  ('lugar','CLASON'),
  ('lugar','COLON'),
  ('lugar','CONCEPCION DEL URUGUAY'),
  ('lugar','CONO SUR'),
  ('lugar','CORDOBA'),
  ('lugar','CORDOBA CAPITAL'),
  ('lugar','CORONEL MOLDES'),
  ('lugar','CORONEL PRINGLES'),
  ('lugar','CORONEL SUAREZ'),
  ('lugar','CORRAL DE BUSTOS'),
  ('lugar','CRESPO'),
  ('lugar','CRUZ ALTA'),
  ('lugar','DON TORCUATO'),
  ('lugar','DOSAM'),
  ('lugar','DOSAM BS AS'),
  ('lugar','EL TREBOL'),
  ('lugar','EMBARCACION'),
  ('lugar','ESPERANZA'),
  ('lugar','ETRURIA'),
  ('lugar','FIRMAT'),
  ('lugar','GALVEZ'),
  ('lugar','GANCEDO'),
  ('lugar','GARIN'),
  ('lugar','GENERAL CABRERA'),
  ('lugar','GENERAL PAZ'),
  ('lugar','GENERAL PICO'),
  ('lugar','GENERAL VILLEGAS'),
  ('lugar','GUALEGUAY'),
  ('lugar','GUALEGUAYCHU'),
  ('lugar','GUATRACHE'),
  ('lugar','GUAYMALLEN'),
  ('lugar','HASENKAMP'),
  ('lugar','HENDERSON'),
  ('lugar','HERMOSO CAMPO'),
  ('lugar','HERNANDO'),
  ('lugar','HUGUES'),
  ('lugar','HUINCA RENANCO'),
  ('lugar','HUMBOLDT'),
  ('lugar','IDIAZABAL'),
  ('lugar','INRIVILLE'),
  ('lugar','INTENDENTE ALVEAR'),
  ('lugar','JESUS MARIA'),
  ('lugar','JOVITA'),
  ('lugar','JUNIN'),
  ('lugar','LA CARLOTA'),
  ('lugar','LA CESIRA'),
  ('lugar','LA PAZ'),
  ('lugar','LA PUERTA'),
  ('lugar','LABOULAYE'),
  ('lugar','LAS LAJITAS'),
  ('lugar','LAS ROSAS'),
  ('lugar','LEONES'),
  ('lugar','LINCOLN'),
  ('lugar','LOBERIA'),
  ('lugar','LOBOS'),
  ('lugar','LOMAS DE ZAMORA'),
  ('lugar','LOS CISNES'),
  ('lugar','LOS JURIES'),
  ('lugar','LOS NOGALES'),
  ('lugar','LOS TOLDOS'),
  ('lugar','LOS ZORROS'),
  ('lugar','MAGGIOLO'),
  ('lugar','MAIPU'),
  ('lugar','MAR DEL PLATA'),
  ('lugar','MARCOS JUAREZ'),
  ('lugar','MATTALDI'),
  ('lugar','MAYOR BURATOVICH'),
  ('lugar','MENDOZA'),
  ('lugar','MONTE BUEY'),
  ('lugar','MONTE CRISTO'),
  ('lugar','NECOCHEA'),
  ('lugar','NOGOYA'),
  ('lugar','OLAVARRIA'),
  ('lugar','ORENSE'),
  ('lugar','PAMPA DEL INFIERNO'),
  ('lugar','PASO DE LA LAGUNA'),
  ('lugar','PEHUAJO'),
  ('lugar','PERGAMINO'),
  ('lugar','PEYRANO'),
  ('lugar','PICHANAL'),
  ('lugar','PIGUE'),
  ('lugar','PILAR'),
  ('lugar','PINEDO'),
  ('lugar','PIQUETE CAVADO'),
  ('lugar','PIÑERO'),
  ('lugar','POZO DEL MOLLE'),
  ('lugar','QUIMILI'),
  ('lugar','RAWSON'),
  ('lugar','REALICO'),
  ('lugar','RECONQUISTA'),
  ('lugar','RECREO'),
  ('lugar','RIO CUARTO'),
  ('lugar','RIO PRIMERO'),
  ('lugar','RIO SEGUNDO'),
  ('lugar','ROJAS'),
  ('lugar','ROSARIO'),
  ('lugar','RUFINO'),
  ('lugar','RUNCIMAN'),
  ('lugar','SALADILLO'),
  ('lugar','SALTA'),
  ('lugar','SALTO'),
  ('lugar','SAN ANDRES DE GILES'),
  ('lugar','SAN ANTONIO DE ARECO'),
  ('lugar','SAN FRANCISCO'),
  ('lugar','SAN JORGE'),
  ('lugar','SAN JOSE DE LA DORMIDA'),
  ('lugar','SAN JUAN'),
  ('lugar','SAN JUSTO'),
  ('lugar','SAN NICOLAS'),
  ('lugar','SAN VICENTE'),
  ('lugar','SANTA ROSA'),
  ('lugar','SANTIAGO TEMPLE'),
  ('lugar','SANTO TOME'),
  ('lugar','SINSACATE'),
  ('lugar','TANDIL'),
  ('lugar','TAU'),
  ('lugar','TEODELINA'),
  ('lugar','TOSQUITA'),
  ('lugar','TRENQUE LAUQUEN'),
  ('lugar','TRES ARROYOS'),
  ('lugar','TUCUMAN'),
  ('lugar','URANGA'),
  ('lugar','URDINARRAIN'),
  ('lugar','VEDIA'),
  ('lugar','VENADO TUERTO'),
  ('lugar','VICTORIA'),
  ('lugar','VICUÑA MACKENA'),
  ('lugar','VILLA CAÑAS'),
  ('lugar','VILLA DE MARIA'),
  ('lugar','VILLA MARIA'),
  ('lugar','VILLA MERCEDES'),
  ('lugar','VILLA SARMIENTO'),
  ('lugar','VILLA TRINIDAD'),
  ('lugar','WHEELWRIGHT'),
  ('lugar','ZARATE'),
  ('lugar','ZAVALLA'),
  ('lugar','ZENON PEREYRA'),
  ('carga','CEREAL'),
  ('carga','AGROQUIMICO'),
  ('carga','ALIMENTO'),
  ('carga','PALLETS'),
  ('carga','BIG BAG'),
  ('carga','CONTENEDOR'),
  ('carga','CONTENEDOR VACIO'),
  ('carga','BIDONES VACIOS'),
  ('carga','LADRILLOS'),
  ('carga','ALGODON'),
  ('carga','SAL'),
  ('carga','SEMILLA'),
  ('carga','FERTILIZANTE'),
  ('carga','PORCELANATO')
on conflict (campo, valor) do nothing;

-- Alias ---------------------------------------------------------------
insert into alias_valores (campo, alias, canonico_id)
select d.campo, d.alias, c.id from (values
  ('lugar','9 DE JLIO','9 DE JULIO'),
  ('lugar','ARECO','SAN ANTONIO DE ARECO'),
  ('lugar','BAHIABLANCA','BAHIA BLANCA'),
  ('lugar','BALL VILLE','BELL VILLE'),
  ('lugar','CAMAPANA','CAMPANA'),
  ('lugar','CAMRNE DE ARECO','CARMEN DE ARECO'),
  ('lugar','CHAPUY YTEODELINA','CHAPUY Y TEODELINA'),
  ('lugar','CHARAT','CHARATA'),
  ('lugar','CHILVILCOY','CHIVILCOY'),
  ('lugar','CONCEPCIO NDEL URUGUAY','CONCEPCION DEL URUGUAY'),
  ('lugar','CORAAL DE BUSTOS','CORRAL DE BUSTOS'),
  ('lugar','CORODOBA','CORDOBA'),
  ('lugar','GALEZ','GALVEZ'),
  ('lugar','GENEERAL PICO','GENERAL PICO'),
  ('lugar','GENREAL CABRERA','GENERAL CABRERA'),
  ('lugar','GUALAGUAY','GUALEGUAY'),
  ('lugar','HERNOSO CAMPO','HERMOSO CAMPO'),
  ('lugar','HUMBOLST','HUMBOLDT'),
  ('lugar','INRRIVILLE','INRIVILLE'),
  ('lugar','LABOLAYE','LABOULAYE'),
  ('lugar','LAS LJITAS','LAS LAJITAS'),
  ('lugar','LOMA DE ZAMORA','LOMAS DE ZAMORA'),
  ('lugar','MAGIOLLO','MAGGIOLO'),
  ('lugar','MAR DEL PALTA','MAR DEL PLATA'),
  ('lugar','MAR EL PLATA','MAR DEL PLATA'),
  ('lugar','MAYOT BURATOVICH','MAYOR BURATOVICH'),
  ('lugar','PERGAINO','PERGAMINO'),
  ('lugar','PICO','GENERAL PICO'),
  ('lugar','PIQUET CABADO','PIQUETE CAVADO'),
  ('lugar','RIO CAURTO','RIO CUARTO'),
  ('lugar','RUDINO','RUFINO'),
  ('lugar','SAN DE GILES','SAN ANDRES DE GILES'),
  ('lugar','SAN FFRANCISCO','SAN FRANCISCO'),
  ('lugar','SSANTO TOME','SANTO TOME'),
  ('lugar','TEDODELINA','TEODELINA'),
  ('lugar','TRENQUE','TRENQUE LAUQUEN'),
  ('lugar','TRENQUE LAUNQUEN','TRENQUE LAUQUEN'),
  ('lugar','TRES AROYYOS','TRES ARROYOS'),
  ('lugar','VENADO','VENADO TUERTO'),
  ('lugar','VICROTIA','VICTORIA'),
  ('lugar','VILLEGAS','GENERAL VILLEGAS'),
  ('lugar','VT','VENADO TUERTO'),
  ('carga','40 PALETS','PALLETS'),
  ('carga','40 PALETTS','PALLETS'),
  ('carga','40 PALLETS BYL','PALLETS'),
  ('carga','AGROQUIMICO DE BYL','AGROQUIMICO'),
  ('carga','AGROQUIMICOS','AGROQUIMICO'),
  ('carga','BB','BIG BAG'),
  ('carga','BIGBAG','BIG BAG'),
  ('carga','CAREAL','CEREAL'),
  ('carga','CONTEINER','CONTENEDOR'),
  ('carga','CONTEINER VACIO','CONTENEDOR VACIO'),
  ('carga','PALETIZADO','PALLETS'),
  ('carga','PALETS','PALLETS'),
  ('carga','PALLET','PALLETS')
) as d(campo, alias, valor)
join valores_canonicos c on c.campo = d.campo and c.valor = d.valor
on conflict (campo, alias) do nothing;

-- Lugares que ya se usan en la base y no son variantes de otro ---------
-- Van al catalogo para que la comparacion por parecido no los 'corrija' contra
-- un pueblo distinto: BANDERALO no es BANDERA, GENERAL PINTO no es GENERAL PICO.
insert into valores_canonicos (campo, valor) values
  ('lugar','30 DE AGOSTO'),
  ('lugar','AGM BS AS'),
  ('lugar','AGUARAY'),
  ('lugar','AIBAR'),
  ('lugar','ALBERDI'),
  ('lugar','ALBERTI'),
  ('lugar','ALCORTA'),
  ('lugar','ALDERETE'),
  ('lugar','ALGUNOS MAS'),
  ('lugar','ALTA GRACIA'),
  ('lugar','ALTA GRACIA CORDOBA'),
  ('lugar','ALTO PELADO'),
  ('lugar','ALTO VERDE'),
  ('lugar','ALTOS DE CHIPON'),
  ('lugar','ALVEAR'),
  ('lugar','ALVIMACA'),
  ('lugar','AMEGHINO'),
  ('lugar','AMENABAR'),
  ('lugar','ANGUIL'),
  ('lugar','ANTA'),
  ('lugar','ARANGUREN'),
  ('lugar','ARAUCARIA'),
  ('lugar','ARENALES'),
  ('lugar','ARENAZA'),
  ('lugar','AREQUITO'),
  ('lugar','ARMSTRONG'),
  ('lugar','ARRECIFES'),
  ('lugar','ARROYO BARU'),
  ('lugar','ARROYO CEIBAL'),
  ('lugar','ARROYO SECO'),
  ('lugar','AUSONIA'),
  ('lugar','AVIA TERAI'),
  ('lugar','BALNEARIA'),
  ('lugar','BANDERALO'),
  ('lugar','BARADERO'),
  ('lugar','BELGRANO'),
  ('lugar','BELLA VISTA'),
  ('lugar','BERROTARAN'),
  ('lugar','BERUTTI'),
  ('lugar','BETBEDER'),
  ('lugar','BIGAND'),
  ('lugar','BRANDES'),
  ('lugar','BS AS TAU'),
  ('lugar','BUNGE TANCACHA'),
  ('lugar','BUSTINZA'),
  ('lugar','CABRERA'),
  ('lugar','CAGILERO'),
  ('lugar','CALCHIN'),
  ('lugar','CAMPO CERCA'),
  ('lugar','CAMPO LARGO'),
  ('lugar','CARLOS PELLEGRINI'),
  ('lugar','CARLOS SPEGAZINI'),
  ('lugar','CARMEN'),
  ('lugar','CARRERAS'),
  ('lugar','CASBAS'),
  ('lugar','CASTELLI'),
  ('lugar','CAVANAGH'),
  ('lugar','CAÑADA DE LUQUE'),
  ('lugar','CAÑADA HONDA'),
  ('lugar','CAÑADA ROSQUIN'),
  ('lugar','CEIBALITO'),
  ('lugar','CERES'),
  ('lugar','CERRITO'),
  ('lugar','CHAÑAR MUYO'),
  ('lugar','CHAÑEAR LADEADO'),
  ('lugar','CINTRA'),
  ('lugar','CIPOLETTI'),
  ('lugar','CIPOLLETTI'),
  ('lugar','CLIENTES'),
  ('lugar','COL AGUERO'),
  ('lugar','COLON BS AS'),
  ('lugar','COLONIA HINOJO'),
  ('lugar','COLONIA SAN BARTOLOME'),
  ('lugar','CONCEPCION'),
  ('lugar','CONCI'),
  ('lugar','CONCORDIA'),
  ('lugar','CORODBA'),
  ('lugar','CORONEL BAIGORRIA'),
  ('lugar','CORTO A UN CAMPO'),
  ('lugar','CURUZU CUATIA'),
  ('lugar','CUYO'),
  ('lugar','DAIREAUX'),
  ('lugar','DAIREUX'),
  ('lugar','DEAN FUNES CORDOBA'),
  ('lugar','DEHEZA'),
  ('lugar','DEL CAMPILLO'),
  ('lugar','DEVOTO'),
  ('lugar','DIAMANTE'),
  ('lugar','DIEGO DE ALVEAR'),
  ('lugar','DRAGONES SALTA'),
  ('lugar','DUDIGNAC'),
  ('lugar','DVA PILAR'),
  ('lugar','EDUARDO CASTEX'),
  ('lugar','EL COLORADO'),
  ('lugar','EL CRISPIN'),
  ('lugar','EL FUERTECITO'),
  ('lugar','EL SOLAR'),
  ('lugar','EL TIO'),
  ('lugar','ELENA'),
  ('lugar','ELORTONDO'),
  ('lugar','EMBALSE'),
  ('lugar','ENTRE RIOS'),
  ('lugar','ETC'),
  ('lugar','EUGENIO BUSTOS'),
  ('lugar','FEDERAL'),
  ('lugar','FIGUERA'),
  ('lugar','FORTIN OLAVARRIA'),
  ('lugar','FRAGA'),
  ('lugar','FRENCH'),
  ('lugar','FRIAS'),
  ('lugar','GAHAN'),
  ('lugar','GALPON'),
  ('lugar','GAONA'),
  ('lugar','GARIN DOSAM'),
  ('lugar','GARMENDIA'),
  ('lugar','GENERAL DEHEZA'),
  ('lugar','GENERAL LAMADRID'),
  ('lugar','GENERAL LEVALLE'),
  ('lugar','GENERAL LOPEZ'),
  ('lugar','GENERAL PINTO'),
  ('lugar','GENERAL RAMIREZ'),
  ('lugar','GENERAL RECEDO'),
  ('lugar','GENERAL ROCA'),
  ('lugar','GENERAL SOLER'),
  ('lugar','GENREAL PINEDO'),
  ('lugar','GERMANIA'),
  ('lugar','GODEKEN'),
  ('lugar','GOULD'),
  ('lugar','GOYA'),
  ('lugar','GRAL ALVEAR'),
  ('lugar','GRAL BELGRANO'),
  ('lugar','GRAL JUAN MADARIAGA'),
  ('lugar','GRAL JUAN MAGARIAGA'),
  ('lugar','GRAL LA MADRID'),
  ('lugar','GRAL LEVALLE'),
  ('lugar','GRAL MANSILLA'),
  ('lugar','GRAL PICO'),
  ('lugar','GRANADERO BAIGORRIA'),
  ('lugar','GUAMINI'),
  ('lugar','GUARDI ESCOLTA'),
  ('lugar','GUATIMOZIN'),
  ('lugar','GUEMES'),
  ('lugar','HERRERA YCHAJARI'),
  ('lugar','INGENIERO WHITE'),
  ('lugar','INT ALVEAR'),
  ('lugar','ISAL VERDE'),
  ('lugar','ISCA YACU'),
  ('lugar','ITIN CHACO'),
  ('lugar','J V GONZALEZ'),
  ('lugar','JUAN JOSE PASO'),
  ('lugar','JUSTO DARAC'),
  ('lugar','JUSTO DARACT'),
  ('lugar','LA ANGELICA'),
  ('lugar','LA ANGELINA'),
  ('lugar','LA ARAUCARIA'),
  ('lugar','LA BANDA'),
  ('lugar','LA CAUTIVA'),
  ('lugar','LA COCHA'),
  ('lugar','LA COHCA'),
  ('lugar','LA LAGUNA'),
  ('lugar','LA PALOMA'),
  ('lugar','LA PARA'),
  ('lugar','LA PELADA SANTA FE'),
  ('lugar','LA PLATA'),
  ('lugar','LA PUNILLA'),
  ('lugar','LA VALERIA'),
  ('lugar','LA VIOLETA'),
  ('lugar','LAGUNA LARGA'),
  ('lugar','LAMADRID'),
  ('lugar','LANDETA'),
  ('lugar','LANTIERI'),
  ('lugar','LARTIRIGOYEN'),
  ('lugar','LAS BREÑAS'),
  ('lugar','LAS BREÑAS CHACO'),
  ('lugar','LAS PAREJAS'),
  ('lugar','LAS PIPINAS'),
  ('lugar','LAS VARILLAS'),
  ('lugar','LAVALLE TUCUMAN'),
  ('lugar','LOS BERROS'),
  ('lugar','LOS MOLINOS'),
  ('lugar','LOS POZOS'),
  ('lugar','LOS POZOS SALTA'),
  ('lugar','LOS QUIRQUINCHOS'),
  ('lugar','LOS SURGENTES'),
  ('lugar','LOZADA'),
  ('lugar','LUJAN BS AS'),
  ('lugar','LUJAN DE CUYO'),
  ('lugar','LUQUE'),
  ('lugar','MACACHIN'),
  ('lugar','MADARIAGA'),
  ('lugar','MALABRIGO'),
  ('lugar','MALAGUEÑO'),
  ('lugar','MANUEL OCAMPO'),
  ('lugar','MARIA SUSANA'),
  ('lugar','MATESUR'),
  ('lugar','MECHITA'),
  ('lugar','MECHONGUE'),
  ('lugar','MERCEDES'),
  ('lugar','MERCEDEZ BS AS'),
  ('lugar','METAN'),
  ('lugar','MIGUEL RIGLOS LA PAMPA'),
  ('lugar','MIRAMAR'),
  ('lugar','MONTE DE LOS GAUCHOS'),
  ('lugar','MONTE DEL ROSARIO'),
  ('lugar','MONTE MAIZ'),
  ('lugar','MORENO BS AS'),
  ('lugar','MORENO SGO'),
  ('lugar','MORRISON'),
  ('lugar','MORTEROS'),
  ('lugar','MUNRO'),
  ('lugar','MURPHY'),
  ('lugar','NAVARRO'),
  ('lugar','NORBERTO DE RIESTRA'),
  ('lugar','NORTE'),
  ('lugar','NUEVA ESPERANZA'),
  ('lugar','NUEVA GALIA'),
  ('lugar','NUEVE DE JULIO'),
  ('lugar','ONCATIVO'),
  ('lugar','ORAN'),
  ('lugar','ORDONEZ'),
  ('lugar','ORDOÑEZ'),
  ('lugar','ORIENTE'),
  ('lugar','OSCAR IMPRESOS'),
  ('lugar','OTROS MAS'),
  ('lugar','PALEMRO OESTE'),
  ('lugar','PALMAR CORDOBA'),
  ('lugar','PARANA'),
  ('lugar','PASCO'),
  ('lugar','PAVON BS AS'),
  ('lugar','PELLEGRINI'),
  ('lugar','PERICO'),
  ('lugar','PIEDRITAS'),
  ('lugar','PIERES'),
  ('lugar','PILA'),
  ('lugar','PINTO SANTIAGO DEL ESTERO'),
  ('lugar','PIQUETE CABADA'),
  ('lugar','PLA'),
  ('lugar','PORTEÑA'),
  ('lugar','POZO HONDO'),
  ('lugar','PUERTO MADERO BS AS'),
  ('lugar','PUERTO TIROL'),
  ('lugar','PUJATO'),
  ('lugar','QUEMU QUEMU'),
  ('lugar','QUEQUEN'),
  ('lugar','RAFAELA'),
  ('lugar','RAIWON GUALEGUAYCHU'),
  ('lugar','RECORRIDO HASTA CORONEL SUAREZ'),
  ('lugar','RECORRIDO HASTA TOSTADO'),
  ('lugar','REDUCCION'),
  ('lugar','RIESTRA'),
  ('lugar','RIO TERCERO'),
  ('lugar','RIVADAVIA'),
  ('lugar','ROLDAN'),
  ('lugar','ROQUE PEREZ'),
  ('lugar','ROQUE SANZ PEÑA'),
  ('lugar','ROSARIO DE LA FRONTERA'),
  ('lugar','ROVERSI'),
  ('lugar','SABATINI'),
  ('lugar','SACHAYOJ'),
  ('lugar','SADER'),
  ('lugar','SAENZ PEÑA'),
  ('lugar','SAFORCADA'),
  ('lugar','SALSIPUEDES'),
  ('lugar','SAMPACHO'),
  ('lugar','SAN A DE ARECO'),
  ('lugar','SAN ANTONIO DE ARECO. COLON'),
  ('lugar','SAN CARLOS CENTRO'),
  ('lugar','SAN FRANCISCO DE CHAÑAR'),
  ('lugar','SAN GREGORIO'),
  ('lugar','SAN JAVIER'),
  ('lugar','SAN JOAQUIN'),
  ('lugar','SAN JOSE DE LA ESQUINA'),
  ('lugar','SAN JUSTO ENTRE RIOS'),
  ('lugar','SAN LORENZO'),
  ('lugar','SAN MANUEL'),
  ('lugar','SAN MIGUEL'),
  ('lugar','SAN MIGUEL DE TUCUMAN'),
  ('lugar','SAN PEDRO'),
  ('lugar','SAN RAFAEL'),
  ('lugar','SANCTI SPRITU'),
  ('lugar','SANTA ISABEL'),
  ('lugar','SANTA LUCIA'),
  ('lugar','SANTA MARGARITA'),
  ('lugar','SANTIAGO'),
  ('lugar','SASTRE'),
  ('lugar','SAUCE VIEJO'),
  ('lugar','SERFIM'),
  ('lugar','SIGMA'),
  ('lugar','STROEDER'),
  ('lugar','TAFI VIEJO'),
  ('lugar','TALAVERA'),
  ('lugar','TARTAGAL'),
  ('lugar','TERMINA EN LOBERIA'),
  ('lugar','TERMINO EN VILLA DE MARIA'),
  ('lugar','TIO PUJIO'),
  ('lugar','TOLEDO'),
  ('lugar','TORNQUIST'),
  ('lugar','TOSTADO'),
  ('lugar','TOTORA'),
  ('lugar','TRANSITO'),
  ('lugar','TRENEL'),
  ('lugar','TRES ISLETAS'),
  ('lugar','TRES LOMAS'),
  ('lugar','TUCURAL'),
  ('lugar','UCACHA'),
  ('lugar','UNO MAS'),
  ('lugar','URIBELARREA'),
  ('lugar','VIALE'),
  ('lugar','VICUÑA'),
  ('lugar','VIDAL'),
  ('lugar','VIEDMA'),
  ('lugar','VILLA ANGELA'),
  ('lugar','VILLA ASCASUBI'),
  ('lugar','VILLA CONCEPCION DEL TIO'),
  ('lugar','VILLA CONSTITUCION'),
  ('lugar','VILLA DEL ROSARIO'),
  ('lugar','VILLA DEL TOTORAL'),
  ('lugar','VILLA ESPIL'),
  ('lugar','VILLA FONTANA'),
  ('lugar','VILLA MAZA'),
  ('lugar','VILLA REGINA'),
  ('lugar','VILLA SENA BS AS'),
  ('lugar','VILLA VALERIA'),
  ('lugar','VILLAGUAY'),
  ('lugar','VVT'),
  ('lugar','WINIFREDA'),
  ('lugar','ZAVALIA')
on conflict (campo, valor) do nothing;
